'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase, Analysis } from '@/lib/supabase';
import { DOMAIN_COLORS, getDomainForStrength } from '@/lib/strengths';
import { useAuth } from '@/components/LoginModal';
import LangToggle from '@/components/LangToggle';
import { useLang } from '@/lib/LanguageContext';


function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
  });
}

function downloadPDF(analysis: Analysis) {
  const displayName = analysis.full_name?.trim() || 'Anonymous';
  const dateStr = analysis.created_at ? formatDate(analysis.created_at) : '';
  const strengths: string[] = analysis.strengths ?? [];

  let data: Record<string, unknown> = {};
  try {
    const cleaned = analysis.analysis.trim()
      .replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/\s*```$/i, '');
    data = JSON.parse(cleaned);
  } catch { /* fallback */ }

  const isRu = analysis.lang === 'ru';
  const L = {
    report: isRu ? 'Отчёт об оценке талантов' : 'Talent Assessment Report',
    domain: isRu ? 'Доминирующий домен' : 'Dominant Domain',
    dna: isRu ? 'ДНК Талантов' : 'Talent DNA',
    superpower: isRu ? 'Суперсила' : 'Superpower',
    interact: isRu ? 'Взаимодействие сильных сторон' : 'How Strengths Interact',
    domainReason: isRu ? 'Почему этот домен?' : 'Domain Reason',
    strengthsLabel: isRu ? 'Топ сильных сторон' : 'Top Strengths',
    blindSpots: isRu ? 'Слепые зоны' : 'Blind Spots',
    famous: isRu ? 'Похожие профили' : 'Similar Profiles',
    careers: isRu ? 'Карьерные пути' : 'Best Career Paths',
    partners: isRu ? 'Идеальные партнёры' : 'Ideal Work Partners',
    footer: isRu ? 'Создано Inner Vector · Оценка талантов' : 'Generated by Inner Vector · Talent Assessment',
  };

  const sec = (label: string, content: string) =>
    content ? `<div class="section"><div class="section-label">${label}</div><div class="section-body">${content}</div></div>` : '';

  const strengthsHtml = strengths.map((s, i) =>
    `<div class="strength-item"><span class="rank">${i + 1}</span>${s}</div>`).join('');

  const blindSpotsHtml = Array.isArray(data.blindSpots)
    ? (data.blindSpots as string[]).map(b => `<div class="bullet">• ${b}</div>`).join('') : '';

  const famousHtml = Array.isArray(data.famousPeople)
    ? (data.famousPeople as {name:string;field:string;whyMatch:string;achievement:string}[]).map(p =>
        `<div class="card"><strong>${p.name}</strong> <span class="field">${p.field}</span><div class="sub">${p.whyMatch}</div><div class="note">${p.achievement}</div></div>`
      ).join('') : '';

  const careersHtml = Array.isArray(data.careers)
    ? (data.careers as {title:string;whyFits:string;firstStep:string}[]).map(c =>
        `<div class="card"><strong>${c.title}</strong><div class="sub">${c.whyFits}</div><div class="note">→ ${c.firstStep}</div></div>`
      ).join('') : '';

  const partnersHtml = Array.isArray(data.idealPartners)
    ? (data.idealPartners as {type:string;topStrengths:string[];whyComplement:string;dynamicInAction:string}[]).map(p =>
        `<div class="card"><strong>${p.type}</strong><div class="tags">${(p.topStrengths||[]).map(s=>`<span class="tag">${s}</span>`).join('')}</div><div class="sub">${p.whyComplement}</div><div class="note">${p.dynamicInAction}</div></div>`
      ).join('') : '';

  const html = `<!DOCTYPE html>
<html lang="${analysis.lang}">
<head>
<meta charset="UTF-8"/>
<title>Inner Vector — ${displayName}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:'Inter',sans-serif;color:#1e2937;background:#fff;font-size:11pt;line-height:1.6}
  .header{background:#0d111e;padding:22px 32px 18px;display:flex;justify-content:space-between;align-items:flex-end}
  .header h1{color:#d4a843;font-size:20pt;font-weight:700}
  .header p{color:#94a3b8;font-size:9pt;margin-top:2px}
  .header-right .name{color:#fff;font-size:13pt;font-weight:600;text-align:right}
  .header-right .date{color:#64748b;font-size:8pt;text-align:right;margin-top:2px}
  .domain-badge{background:#d4a84312;border-left:3px solid #d4a843;padding:7px 32px;font-size:8.5pt;font-weight:700;color:#d4a843;letter-spacing:.1em;text-transform:uppercase}
  .content{padding:18px 32px}
  .section{margin-bottom:16px;break-inside:avoid}
  .section-label{font-size:7pt;font-weight:700;text-transform:uppercase;letter-spacing:.12em;color:#64748b;background:#f1f5f9;padding:3px 8px;border-radius:3px;margin-bottom:6px}
  .section-body{font-size:10pt;color:#1e2937;line-height:1.65}
  .strengths-grid{display:grid;grid-template-columns:1fr 1fr;gap:3px 20px}
  .strength-item{display:flex;align-items:center;gap:7px;padding:2px 0;font-size:10pt}
  .rank{background:#f1f5f9;color:#64748b;font-weight:700;font-size:7.5pt;width:19px;height:19px;border-radius:50%;display:flex;align-items:center;justify-content:center;flex-shrink:0}
  .bullet{padding:2px 0;font-size:10pt;color:#334155}
  .card{padding:7px 0;border-bottom:1px solid #f1f5f9}
  .card:last-child{border-bottom:none}
  .field{font-size:8pt;color:#64748b;font-style:italic}
  .sub{font-size:9.5pt;color:#475569;margin-top:3px;line-height:1.5}
  .note{font-size:8.5pt;color:#94a3b8;margin-top:2px;font-style:italic}
  .tags{display:flex;flex-wrap:wrap;gap:3px;margin:3px 0}
  .tag{background:#f1f5f9;color:#475569;font-size:7.5pt;padding:2px 7px;border-radius:10px}
  .footer{border-top:1px solid #f1f5f9;padding:9px 32px;display:flex;justify-content:space-between;font-size:7.5pt;color:#94a3b8;margin-top:10px}
  @media print{body,html{-webkit-print-color-adjust:exact;print-color-adjust:exact}.header,.domain-badge{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style>
</head>
<body>
<div class="header">
  <div><h1>Inner Vector</h1><p>${L.report}</p></div>
  <div class="header-right"><div class="name">${displayName}</div><div class="date">${dateStr}</div></div>
</div>
<div class="domain-badge">${L.domain}: ${(data.dominantDomain as string) || ''}</div>
<div class="content">
  ${sec(L.dna, (data.talentDNA as string)||'')}
  ${sec(L.superpower, (data.superpower as string)||'')}
  ${sec(L.interact, (data.strengthsInteraction as string)||'')}
  ${sec(L.domainReason, (data.domainReason as string)||'')}
  <div class="section"><div class="section-label">${L.strengthsLabel}</div><div class="strengths-grid">${strengthsHtml}</div></div>
  ${blindSpotsHtml ? `<div class="section"><div class="section-label">${L.blindSpots}</div><div class="section-body">${blindSpotsHtml}</div></div>` : ''}
  ${famousHtml ? `<div class="section"><div class="section-label">${L.famous}</div><div class="section-body">${famousHtml}</div></div>` : ''}
  ${careersHtml ? `<div class="section"><div class="section-label">${L.careers}</div><div class="section-body">${careersHtml}</div></div>` : ''}
  ${partnersHtml ? `<div class="section"><div class="section-label">${L.partners}</div><div class="section-body">${partnersHtml}</div></div>` : ''}
</div>
<div class="footer"><span>${L.footer}</span><span>${dateStr}</span></div>
</body></html>`;

  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.onload = () => { win.print(); };
}


export default function HistoryPage() {
  const router = useRouter();
  const { authed } = useAuth();
  const { lang } = useLang();
  const [analyses, setAnalyses] = useState<Analysis[]>([]);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState<string | null>(null);
  const [search, setSearch] = useState('');

  useEffect(() => {
    if (authed === false) { router.replace('/'); return; }
    if (authed === null) return;

    supabase
      .from('analyses')
      .select('*')
      .order('created_at', { ascending: false })
      .then(({ data }) => {
        setAnalyses(data ?? []);
        setLoading(false);
      });
  }, [authed, router]);

  if (authed === null || loading) {
    return <div className="min-h-screen bg-radial" />;
  }

  const filtered = analyses.filter((a) =>
    (a.full_name ?? '').toLowerCase().includes(search.toLowerCase())
  );

  const handleDownload = async (a: Analysis) => {
    setDownloading(a.id ?? '');
    await downloadPDF(a);
    setDownloading(null);
  };

  return (
    <div className="min-h-screen bg-radial flex flex-col">
      {/* Top bar */}
      <div className="flex items-center justify-between px-6 pt-5 pb-4 border-b border-white/5">
        <div className="flex items-center gap-3">
          <button
            onClick={() => router.push('/')}
            className="flex items-center gap-2 text-slate-400 hover:text-white text-sm transition-colors"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
            </svg>
            {lang === 'ru' ? 'Назад' : 'Back'}
          </button>
          <span className="text-white/10">|</span>
          <span className="text-gold/70 text-xs font-medium tracking-widest uppercase">
            {lang === 'ru' ? 'История анализов' : 'Analysis History'}
          </span>
        </div>
        <LangToggle />
      </div>

      <main className="flex-1 max-w-3xl mx-auto w-full px-4 py-8">

        {/* Header */}
        <div className="mb-6 flex items-center justify-between gap-4 flex-wrap">
          <div>
            <h1 className="font-serif text-3xl font-bold text-white">
              {lang === 'ru' ? 'Все профили' : 'All Profiles'}
            </h1>
            <p className="text-slate-500 text-sm mt-1">
              {filtered.length} {lang === 'ru' ? 'записей' : 'records'}
            </p>
          </div>

          {/* Search */}
          <div className="relative">
            <div className="absolute inset-y-0 left-3 flex items-center pointer-events-none">
              <svg className="w-4 h-4 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
            </div>
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder={lang === 'ru' ? 'Поиск по имени...' : 'Search by name...'}
              className="bg-white/5 border border-white/10 rounded-xl pl-9 pr-4 py-2 text-slate-200 placeholder-slate-500 focus:outline-none focus:border-gold/40 transition-all text-sm w-52"
            />
          </div>
        </div>

        {/* List */}
        {filtered.length === 0 ? (
          <div className="text-center py-20 text-slate-600">
            <svg className="w-10 h-10 mx-auto mb-3 opacity-30" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            {lang === 'ru' ? 'Нет записей' : 'No records found'}
          </div>
        ) : (
          <div className="space-y-3">
            {filtered.map((a, idx) => {
              const strengths: string[] = a.strengths ?? [];
              const isDownloading = downloading === a.id;

              return (
                <div
                  key={a.id ?? idx}
                  className="group flex items-center gap-4 p-4 rounded-2xl border border-white/8 bg-white/3 hover:bg-white/5 hover:border-white/12 transition-all duration-200"
                >
                  {/* Index */}
                  <div className="flex-shrink-0 w-8 h-8 rounded-full bg-white/5 border border-white/10 flex items-center justify-center text-slate-500 text-xs font-bold">
                    {idx + 1}
                  </div>

                  {/* Info */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1.5">
                      <span className="text-white font-semibold text-sm truncate">
                        {a.full_name?.trim() || <span className="text-slate-600 italic">Anonymous</span>}
                      </span>
                      <span className="text-slate-600 text-xs flex-shrink-0">
                        {a.created_at ? formatDate(a.created_at) : ''}
                      </span>
                    </div>

                    {/* Strength dots */}
                    <div className="flex flex-wrap gap-1">
                      {strengths.slice(0, 10).map((s, i) => {
                        const domain = getDomainForStrength(s);
                        const colors = domain ? DOMAIN_COLORS[domain] : null;
                        return (
                          <span
                            key={s}
                            title={`${i + 1}. ${s}`}
                            className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs border ${colors ? `${colors.bg} ${colors.text} ${colors.border}` : 'bg-white/5 text-slate-400 border-white/10'}`}
                          >
                            <span className="opacity-50 text-[10px] font-bold">{i + 1}</span>
                            {s}
                          </span>
                        );
                      })}
                    </div>
                  </div>

                  {/* Download PDF */}
                  <button
                    onClick={() => handleDownload(a)}
                    disabled={isDownloading}
                    className="flex-shrink-0 flex items-center gap-2 px-4 py-2 rounded-xl bg-gold/10 border border-gold/20 text-gold text-xs font-medium hover:bg-gold/20 transition-all duration-200 disabled:opacity-50"
                    title="Download PDF"
                  >
                    {isDownloading ? (
                      <span className="w-3.5 h-3.5 border-2 border-gold/30 border-t-gold rounded-full animate-spin" />
                    ) : (
                      <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                    )}
                    PDF
                  </button>
                </div>
              );
            })}
          </div>
        )}
      </main>

      <footer className="text-center py-6 text-slate-600 text-xs border-t border-white/5">
        Inner Vector · Talent Assessment
      </footer>
    </div>
  );
}
